sudo: required
dist: xenial
cache: pip
language: python
python:
- 3.8-dev
- 3.8
- 3.7-dev
- 3.7
- 3.6
- 3.5
#  PyPy versions
- pypy3
matrix:
  allow_failures:
  - python: pypy3
branches:
  only:
  - master
  - dev
  - enhancements
  - "/v\\d+\\.\\d+[a-z]*.\\d+[a-z]*/"
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: SekouDiaoNlp
  on:
    python: 3.7-dev
    repo: DiaoSekouNlp/mlconjug3
    tags: true
    branch: master
  password:
    secure: AZNuESC7kyt+6tbkuEBx6Wh/T2YpcwtU1M5zLDRQzDks3tKmbSf5OD5Q7Hlfn8Bk+PDVCrGp2xfT//WGqntCbIu9lIyGrbmChTSQllSqYopw9GffMF2rzSdxCaKmW6LcgdhWX4oHHjF9vNZEYeZDAyuakH4OesQkRi08HXl5Td3bIJcTlsrPk46g7T20N1klzcA5EJex/8Z4UH/joYIksIuK7EzsjmuTFJBl7mTmmaEIXNs3SBcbuj/ptxPDMrNk1IG+xVkhTQ6tk7ugqfwjGcvrTldB5QA5RUj6Rqoagobhy9GD8Q6Hoe7jWzpy96mgIrwDUAc9I1gq1BtwUJIRTnsK/3r19bWZJ9N6vD5OONKKAHn+m7iBbaRW3Qn/b05TlcIZrWvA0sLEuIp7nVgnZmDyQqC0fCFsfXRt35BqCXsz4gqN8Nb+tvNHTX4ujLwNpZUaaYKYVjmY9M4KxMvKk1nQp6WIrZvfHcomb1UyWaLGqIbyjY+6tBoi4nnb/ImmRdU/FwvMKn9CllVZTr6FgmN9vKB6rj5Wi3YW/v9ZXO5kUuUd9ODcyvVPPbUZ5A51hd1BEiv0btGvHQDt3vNlEP/A8YgdkxjpY5S6W9HkmblEz6lpShuokkxHICX7OM3aCdOQktEK9Etq6vHWSK1JMVsmVSQfdlTplEdw7Qpvnb0=
install: pip install -U tox-travis
script: tox

