sudo: required
dist: trusty
cache: pip
language: python
python:
- 3.6
- 3.5
- 3.4
- 3.7-dev
#  PyPy versions
- pypy3.5
matrix:
  allow_failures:
  - python: pypy3.5
  - python: 3.5
  - python: 3.4
  - python: 3.7-dev
branches:
  only:
  - master
  - dev
  - "/v\\d+\\.\\d+[a-z]*.\\d+[a-z]*/"
install: pip install -U tox-travis
jobs:
  include:
    - stage: test
      script: tox
    - name: train
      script: sudo ./utils/train_models.py

