coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 2%
        informational: false

    patch:
      default:
        target: 75%
        threshold: 2%
        informational: false

ignore:
  - "**/*.yaml"
  - "**/*.yml"
