coverage:
  status:
    project:
      default:
        # Do not fail PRs if the code coverage drops.
        target: 0%
        threshold: 40%
        if_ci_failed: success
        informational: true

steps:
  # (Other steps go here)
  - name: "Upload coverage to Codecov"
    uses: codecov/codecov-action@v1
    with:
      if_ci_failed: success

ignore:
  - "**/*.yaml"
  - "**/*.yml"

