coverage:
  status:
    project:
      default:
        # Do not fail PRs if the code coverage drops.
        target: 0%
        threshold: 10%

steps:
  # (Other steps go here)
  - name: "Upload coverage to Codecov"
    uses: codecov/codecov-action@v1
    with:
      fail_ci_if_error: false

ignore:
  - "**/*.yaml"
  - "**/*.yml"

