coverage:
  status:
    project: false

steps:
  # (Other steps go here)
  - name: "Upload coverage to Codecov"
    uses: codecov/codecov-action@v1
    with:
      fail_ci_if_error: false

ignore:
  - "**/*.yaml"
  - "**/*.yml"

