# constants.toml

[[RESOURCE_PACKAGE]]
RESOURCE_PACKAGE = "mlconjug3"

[[LANGUAGES]]
LANGUAGES = ["default", "fr", "en", "es", "it", "pt", "ro"]

[[SUPPORTED_LANGUAGES]]
SUPPORTED_LANGUAGES = ["default", "en", "es", "fr", "it", "pt", "ro"]

[[TRANSLATED_LANGUAGES]]
TRANSLATED_LANGUAGES = ["en", "es", "fr", "it", "pt", "ro"]

[[LANGUAGE_FULL]]
[LANGUAGE_FULL.fr] = "Français"
[LANGUAGE_FULL.en] = "English"
[LANGUAGE_FULL.es] = "Español"
[LANGUAGE_FULL.it] = "Italiano"
[LANGUAGE_FULL.pt] = "Português"
[LANGUAGE_FULL.ro] = "Română"

[[TRANSLATIONS_PATH]]
TRANSLATIONS_PATH = "/path/to/mlconjug3/locale"

[[VERBS_RESOURCE_PATH]]
[VERBS_RESOURCE_PATH.fr] = "/path/to/mlconjug3/data/conjug_manager/verbs-fr.json"
[VERBS_RESOURCE_PATH.it] = "/path/to/mlconjug3/data/conjug_manager/verbs-it.json"
[VERBS_RESOURCE_PATH.es] = "/path/to/mlconjug3/data/conjug_manager/verbs-es.json"
[VERBS_RESOURCE_PATH.en] = "/path/to/mlconjug3/data/conjug_manager/verbs-en.json"
[VERBS_RESOURCE_PATH.pt] = "/path/to/mlconjug3/data/conjug_manager/verbs-pt.json"
[VERBS_RESOURCE_PATH.ro] = "/path/to/mlconjug3/data/conjug_manager/verbs-ro.json"


[[LANGUAGE_FULL]]
    [LANGUAGE_FULL.fr] = "Français"
    [LANGUAGE_FULL.en] = "English"
    [LANGUAGE_FULL.es] = "Español"
    [LANGUAGE_FULL.it] = "Italiano"
    [LANGUAGE_FULL.pt] = "Português"
    [LANGUAGE_FULL.ro] = "Română"

[translations_path]
path = "locale"

[verbs_resource_path]
fr = "data/conjug_manager/verbs-fr.json"
it = "data/conjug_manager/verbs-it.json"
es = "data/conjug_manager/verbs-es.json"
en = "data/conjug_manager/verbs-en.json"
pt = "data/conjug_manager/verbs-pt.json"
ro = "data/conjug_manager/verbs-ro.json"

[conjugations_resource_path]
fr = "data/conjug_manager/conjugation-fr.json"
it = "data/conjug_manager/conjugation-it.json"
es = "data/conjug_manager/conjugation-es.json"
en = "data/conjug_manager/conjugation-en.json"
pt = "data/conjug_manager/conjugation-pt.json"
ro = "data/conjug_manager/conjugation-ro.json"

[pre_trained_model_path]
fr = "data/models/trained_model-fr-final.zip"
it = "data/models/trained_model-it-final.zip"
es = "data/models/trained_model-es-final.zip"
en = "data/models/trained_model-en-final.zip"
pt = "data/models/trained_model-pt-final.zip"
ro = "data/models/trained_model-ro-final.zip"

[abbrevs]
all = ["1s", "2s", "3s", "1p", "2p", "3p"]

[pronouns]
fr = {abbrev = ["1s", "2s", "3s", "1p", "2p", "3p"], pronoun = ["je", "tu", "il (elle, on)", "nous", "vous", "ils (elles)"]}
it = {abbrev = ["1s", "2s", "3s", "1p", "2p", "3p"], pronoun = ['io', 'tu', 'egli/ella', 'noi', 'voi', 'essi/esse']}
es = {abbrev = ["1s", "2s", "3s", "1p", "2p", "3p"], pronoun = ['yo', 'tú', 'él', 'nosotros', 'vosotros', 'ellos']}
en = {abbrev = ["1s", "2s", "3s", "1p", "2p", "3p"], pronoun = ['I', 'you', 'he/she/it', 'you', 'we', 'they']}
pt = {abbrev = ["1s", "2s", "3s", "1p", "2p", "3p"], pronoun = ['eu', 'você', 'ele/ela', 'nós', 'vocês', 'eles/elas']}
ro = {abbrev = ["1s", "2s", "3s", "1p", "2p", "3p"], pronoun = ['eu', 'tu', 'el', 'noi', 'voi', 'ei/ele']}

[IMPERATIVE_PRONOUNS]
    [IMPERATIVE_PRONOUNS.fr]
        abbrev = ["2s", "1p", "2p"]
        pronoun = ["", "", ""]
    [IMPERATIVE_PRONOUNS.it]
        abbrev = null
        pronoun = null
    [IMPERATIVE_PRONOUNS.es]
        abbrev = ["2s", "3s", "1p", "2p", "3p"]
        pronoun = ['tú', 'él', 'nosotros', 'vosotros', 'ellos']
    [IMPERATIVE_PRONOUNS.en]
        abbrev = ["2s", "1p", "2p"]
        pronoun = ["", "let's", ""]
    [IMPERATIVE_PRONOUNS.pt]
        abbrev = null
        pronoun = null
    [IMPERATIVE_PRONOUNS.ro]
        abbrev = ["2s", "2p"]
        pronoun = ["tu", "voi"]

[AUXILIARIES]
    fr = null
    it = "non"
    es = "no"
    en = null
    pt = "não"
    ro = "nu"

[GENDER]
    [GENDER.fr]
        abbrev = ["ms", "mp", "fs", "fp"]
        pronoun = ["masculin singulier", "masculin pluriel", "feminin singulier", "feminin pluriel"]
    [GENDER.it] = null
    [GENDER.es] = null
    [GENDER.en] = null
    [GENDER.pt] = null
    [GENDER.ro] = null

[NEGATION]
    fr = "ne"
    it = "non"
    es = "no"
    en = "don't"
    pt = "não"
    ro = "nu"

[ALPHABET]
    [ALPHABET.fr]
        vowels = "aáàâeêéèiîïoôöœuûùy"
        consonants = "bcçdfghjklmnpqrstvwxyz"
    [ALPHABET.en]
        vowels = "aeiouy"
        consonants = "bcdfghjklmnpqrstvwxyz"
    [ALPHABET.es]
        vowels = "aáeiíoóuúy"
        consonants = "bcdfghjklmnñpqrstvwxyz"
    [ALPHABET.it]
        vowels = "aàeéèiìîoóòuùy"
        consonants = "bcdfghjklmnpqrstvwxyz"
    [ALPHABET.pt]
        vowels = "aàãááeêéiíoóõuúy"
        consonants = "bcçdfghjklmnpqrstvwxyz"
    [ALPHABET.ro]
        vowels = "aăâeiîouy"
        consonants = "bcdfghjklmnpqrsșştțţvwxyz"



