[languages]
supported = ["fr", "en", "es", "it", "pt", "ro"]
translated = ["fr", "en", "es", "it", "pt", "ro"]

[language_full]
fr = "Français"
en = "English"
es = "Español"
it = "Italiano"
pt = "Português"
ro = "Română"

[verbs]
fr = "VerbFr"
en = "VerbEn"
es = "VerbEs"
it = "VerbIt"
pt = "VerbPt"
ro = "VerbRo"

[pre_trained_model_path]
fr = "data/models/trained_model-fr-final.zip"
it = "data/models/trained_model-it-final.zip"
es = "data/models/trained_model-es-final.zip"
en = "data/models/trained_model-en-final.zip"
pt = "data/models/trained_model-pt-final.zip"
ro = "data/models/trained_model-ro-final.zip"

[alphabet]
fr = { vowels = "aáàâeêéèiîïoôöœuûùy", consonants = "bcçdfghjklmnpqrstvwxyz" }
en = { vowels = "aeiouy", consonants = "bcdfghjklmnpqrstvwxyz" }
es = { vowels = "aáeiíoóuúy", consonants = "bcdfghjklmnñpqrstvwxyz" }
it = { vowels = "aàeéèiìîoóòuùy", consonants = "bcdfghjklmnpqrstvwxyz" }
pt = { vowels = "aàãááeêéiíoóõuúy", consonants = "bcçdfghjklmnpqrstvwxyz" }
ro = { vowels = "aăâeiîouy", consonants = "bcdfghjklmnpqrsșştțţvwxyz" }

[verbs_resource_path]
fr = "data/conjug_manager/verbs-fr.json"
it = "data/conjug_manager/verbs-it.json"
es = "data/conjug_manager/verbs-es.json"
en = "data/conjug_manager/verbs-en.json"
pt = "data/conjug_manager/verbs-pt.json"
ro = "data/conjug_manager/verbs-ro.json"

[conjugations_resource_path]
fr = "data/conjug_manager/conjugations-fr.json"
it = "data/conjug_manager/conjugations-it.json"
es = "data/conjug_manager/conjugations-es.json"
en = "data/conjug_manager/conjugations-en.json"
pt = "data/conjug_manager/conjugations-pt.json"
ro = "data/conjug_manager/conjugations-ro.json"



