# config.yaml

language: fr

output_folder: models

split_proportion: 0.8

dataset:
  class: mlconjug3.DataSet
  args:
    -
      class: mlconjug3.Verbiste
      args:
        - fr

model:
  class: mlconjug3.Model
  args:
    - fr
    -
      class: mlconjug3.CountVectorizer
      args:
        -
          class: mlconjug3.feature_extractor.extract_verb_features
          args:
            - fr
            - (2, 7)
      kwargs:
        binary: true
        lowercase: false
    -
      class: mlconjug3.SelectFromModel
      args:
        -
          class: mlconjug3.LinearSVC
          kwargs:
            penalty: l1
            max_iter: 12000
            dual: false
            verbose: 0
    -
      class: mlconjug3.SGDClassifier
      kwargs:
        loss: log
        penalty: elasticnet
        l1_ratio: 0.15
        max_iter: 40000
        alpha: 1e-5
        verbose: 0
