name: "Build package and run multiple tests"

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
        - os: ubuntu-latest
          path: ~/.cache/pip
        - os: macos-latest
          path: ~/Library/Caches/pip
        - os: windows-latest
          path: ~\AppData\Local\pip\Cache
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - uses: actions/cache@v2
        with:
          path: ${{ matrix.path }}
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements_dev.txt') }}
      - name: Install dependencies
        run: |
            python -m pip install wheel pytest pytest-cov codecov
            pip install -r requirements.txt
            pip install -r requirements_dev.txt

      - name: Build wheels
        run: pip wheel -w DEST_DIR .
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value
      - name: Run tests with pytest, mypy, coverage, bandit and restructuredtext check
        run: |
            py.test --cov=./mlconjug3/
            mypy --strict --ignore-missing-imports  mlconjug3/
            codecov --token=06406f4a-05a0-4974-a902-20fd09de8b50
            bandit -r mlconjug3/
            python setup.py sdist bdist_wheel
            twine check dist/*
        #   python setup.py check --restructuredtext -s
        #   This command has been deprecated. Use `twine check` instead.

  build:
      name: Build source package on ${{ matrix.os }}
      runs-on: ${{ matrix.os }}
      strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macOS-latest]
            include:
            - os: ubuntu-latest
              path: ~/.cache/pip
            - os: macos-latest
              path: ~/Library/Caches/pip
            - os: windows-latest
              path: ~\AppData\Local\pip\Cache
            python-version: [ 3.6, 3.7, 3.8, 3.9 ]

      steps:
          -   uses: actions/checkout@v2
          -   name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
          - uses: actions/cache@v2
            with:
              path: ${{ matrix.path }}
              key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements_dev.txt') }}
          -   name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install flake8 pytest pytest-cov codecov
                  pip install -r requirements.txt
                  pip install -r requirements_dev.txt
          -   name: Run tests with pytest, mypy, coverage, bandit and restructuredtext check
              run: |
                  py.test --cov=./mlconjug3/
                  mypy --strict --ignore-missing-imports  mlconjug3/
                  codecov --token=06406f4a-05a0-4974-a902-20fd09de8b50
                  bandit -r mlconjug3/
                  python setup.py sdist bdist_wheel
                  twine check dist/*
              #   python setup.py check --restructuredtext -s
              #   This command has been deprecated. Use `twine check` instead.
