name: "Manually sign and publish tp pypi"

on: [ workflow_dispatch ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
    build_wheels_with_setuptools:
        name: Build setuptool packages on ${{ matrix.os }} on ${{ matrix.python-version }}
        runs-on: ${{ matrix.os }}
        permissions:
          id-token: write
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                include:
                    -   os: ubuntu-latest
                        path: ~/.cache/pip
                    # -   os: macos-latest
                        # path: ~/Library/Caches/pip
                    # -   os: windows-latest
                        # path: ~\AppData\Local\pip\Cache
                python-version: [ '3.11']

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3 # v2.3.1
              with:
                egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

            -   uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

            -   uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
                with:
                    python-version: ${{ matrix.python-version }}

            -   uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
                with:
                    path: ${{ matrix.path }}
                    key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements_dev.txt') }}
            -   name: Install dependencies
                run: |
                    python -m pip install wheel pytest pytest-cov codecov pandas pyxlsb types-setuptools
                    pip install -r requirements_dev.txt            
          #  -   name: Run bandit
            #    run: bandit -r mlconjug3/ -c .bandit.yml
            -   name: Run PyTest with coverage
                run: |
                    py.test --cov=./mlconjug3/
            -   name: Build wheel using pip
                run: pip wheel -w DEST_DIR .
                    # to supply options, put them in 'env', like:
                    # env:
                #   CIBW_SOME_OPTION: value
            -   name: Build package using setup.py
                run: |
                    python setup.py sdist bdist_wheel
            -   name: Sign package with sigstore
                uses: sigstore/gh-action-sigstore-python@9ea3c9d0bed14de820f1ce678e194c250580feb4 # v1.1.0
                with:
                  inputs: dist/*.tar.gz dist/*.whl
            -   name: Publish a Python distribution to PyPI
                uses: pypa/gh-action-pypi-publish@c7f29f7adef1a245bd91520e94867e5c6eedddcc # release/v1
                with:
                  password: ${{ secrets.PYPI_TOKEN }}
            -   name: Upload coverage artifacts to codecov
                run: codecov --token=06406f4a-05a0-4974-a902-20fd09de8b50


