name: "Manually sign and publish tp pypi"

on: [ workflow_dispatch ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
    build_wheels_with_setuptools:
        name: Build setuptool packages on ${{ matrix.os }} on ${{ matrix.python-version }}
        runs-on: ${{ matrix.os }}
        permissions:
          id-token: write
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                include:
                    -   os: ubuntu-latest
                        path: ~/.cache/pip
                    # -   os: macos-latest
                        # path: ~/Library/Caches/pip
                    # -   os: windows-latest
                        # path: ~\AppData\Local\pip\Cache
                python-version: [ '3.11']

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
              with:
                egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

            -   uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

            -   uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
                with:
                    python-version: ${{ matrix.python-version }}

            -   uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
                with:
                    path: ${{ matrix.path }}
                    key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements_dev.txt') }}
            -   name: Install dependencies
                run: |
                    python -m pip install wheel pytest pytest-cov codecov pandas pyxlsb types-setuptools
                    pip install -r requirements_dev.txt            
          #  -   name: Run bandit
            #    run: bandit -r mlconjug3/ -c .bandit.yml
            -   name: Run PyTest with coverage
                run: |
                    py.test --cov=./mlconjug3/
            -   name: Build wheel using pip
                run: pip wheel -w DEST_DIR .
                    # to supply options, put them in 'env', like:
                    # env:
                #   CIBW_SOME_OPTION: value
            -   name: Build package using setup.py
                run: |
                    python setup.py sdist bdist_wheel
            -   name: Publish a Python distribution to PyPI
                uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e # release/v1
                with:
                  password: ${{ secrets.PYPI_TOKEN }}
            -   name: Sign package with sigstore
                uses: sigstore/gh-action-sigstore-python@9310933b45d7dfc2fe40c1d701ac114548c28d31 # v2.0.1
                with:
                  inputs: dist/*.tar.gz dist/*.whl
            -   name: Upload coverage artifacts to codecov
                run: codecov --token=06406f4a-05a0-4974-a902-20fd09de8b50


