name: "Manually sign and publish tp pypi"

on: [ workflow_dispatch ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    build_wheels_with_setuptools:
        name: Build setuptool packages on ${{ matrix.os }} on ${{ matrix.python-version }}
        runs-on: ${{ matrix.os }}
        permissions:
          id-token: write
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                include:
                    -   os: ubuntu-latest
                        path: ~/.cache/pip
                    # -   os: macos-latest
                        # path: ~/Library/Caches/pip
                    # -   os: windows-latest
                        # path: ~\AppData\Local\pip\Cache
                python-version: [ '3.11']

        steps:
            -   uses: actions/checkout@v3

            -   uses: actions/setup-python@v4
                with:
                    python-version: ${{ matrix.python-version }}

            -   uses: actions/cache@v3
                with:
                    path: ${{ matrix.path }}
                    key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}-${{ hashFiles('**/requirements_dev.txt') }}
            -   name: Install dependencies
                run: |
                    python -m pip install wheel pytest pytest-cov codecov pandas pyxlsb types-setuptools
                    pip install -r requirements_dev.txt            
          #  -   name: Run bandit
            #    run: bandit -r mlconjug3/ -c .bandit.yml
            -   name: Run PyTest with coverage
                run: |
                    py.test --cov=./mlconjug3/
            -   name: Build wheel using pip
                run: pip wheel -w DEST_DIR .
                    # to supply options, put them in 'env', like:
                    # env:
                #   CIBW_SOME_OPTION: value
            -   name: Build package using setup.py
                run: |
                    python setup.py sdist bdist_wheel
            -   name: Sign package with sigstore
                uses: sigstore/gh-action-sigstore-python@v1.0.0
                with:
                  inputs: dist/*.tar.gz dist/*.whl
            -   name: Publish a Python distribution to PyPI
                uses: pypa/gh-action-pypi-publish@release/v1
                with:
                  password: ${{ secrets.PYPI_TOKEN }}
            -   name: Upload coverage artifacts to codecov
                run: codecov --token=06406f4a-05a0-4974-a902-20fd09de8b50


