# A sample workflow which checks out your Infrastructure as Code Configuration files,
# such as Kubernetes, Helm & Terraform and scans them for any security issues.
# The results are then uploaded to GitHub Security Code Scanning
#
# For more examples, including how to limit scans to only high-severity issues
# and fail PR checks, see https://github.com/snyk/actions/
name: Workflow for Python using Snyk 
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read

jobs:
  security:
    if: github.actor!= 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python-3.8@e25b2e6f5658d1bb7a6671b113260f13134cc3af # master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
