name: Build source and wheels packages and upload them to PyPI

# Build on every branch push, tag push, and pull request change:
# on: [workflow_dispatch]
# Alternatively, to publish when a (published) GitHub Release is created, use the following:
on:
  workflow_dispatch:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
    build_wheels_with_poetry:
        name: Build poetry packages on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        permissions: write-all
         #  id-token: write
        defaults:
            run:
                shell: bash
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                include:
                    -   os: ubuntu-latest
                        path: ~/.cache/pip
                python-version: [ 3.9 ]

        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
              with:
                egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

            -   uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0

            -   uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1 # v4.7.0
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Install Poetry
                uses: snok/install-poetry@93ada01c735cc8a383ce0ce2ae205a21c415379b # v1.3.4
                with:
                    virtualenvs-create: true
                    virtualenvs-in-project: true
            -   name: Load cached venv
                id: cached-pip-wheels
                uses: actions/cache@627f0f41f6904a5b1efbaed9f96d9eb58e92e920 # v3.2.4
                with:
                    path: ~/.cache
                    key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
            -   name: Install dependencies
                run: poetry install --no-interaction --no-root
            -   name: Install Package
                run: poetry install --no-interaction
            -   run: |
                   source $VENV
                   poetry --version
            -   name: Run Type Checker
                run: |
                    poetry run pip install types-setuptools
                    poetry run mypy
            -   name: Run Pytest with coverage
                run: poetry run pytest --cov=./mlconjug3/
            -   name: Upload coverage artifacts to codecov
                run: poetry run codecov --token=06406f4a-05a0-4974-a902-20fd09de8b50
            -   name: Build Package
                run: poetry build
            -   name: Sign with sigstore
                uses: sigstore/gh-action-sigstore-python@9310933b45d7dfc2fe40c1d701ac114548c28d31 # v2.0.1
                with:
                  upload-signing-artifacts: true
                  release-signing-artifacts: true
                  inputs: dist/*.tar.gz dist/*.whl
            # -   name: Run Bandit
                # run: poetry run bandit -r mlconjug3/ -c .bandit.yml
            
            -   name: Upload Package to PyPi
                run: |
                    poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
                    poetry publish
